version: '3'
services:
  api:
    container_name: api
    build: ./api/
    links:
      - db
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/web  

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
     - ./db/:/var/lib/postgresql